# Importing Christenson Transcription

We import Christensons direct transcription of the original Ximenez edition.

In [1]:
# quote_char = "’"

In [2]:
import pandas as pd
import numpy as np
from glob import glob 
import plotly_express as px
pd.set_option('display.max_columns', None)

In [3]:
OHCO = ['folio_num', 'side', 'lb_num', 'para_num']

Import into data frame.

In [4]:
ct_file_name =  'christenson-transcription-MOD.txt'
ct_text = open(ct_file_name, "r").readlines()
CT = pd.DataFrame({'line_str': ct_text})
CT.index.name = 'line_id'

In [5]:
CT.head()

                                     line_str
line_id
0                             Folio 1 recto\n
1                                          \n
2                             ARE V XE OHER\n
3                    Tzih varal Quiche vbi.\n
4             Varal xchicatzibah vi xchica-\n

Grab folio and side information.

In [6]:
CT.loc[CT.line_str.str.match("^Folio"), "folio_str"] = CT.line_str.str.split()
CT.folio_str = CT.folio_str.ffill()

In [7]:
CT = pd.concat([CT, CT.folio_str.apply(pd.Series)], axis=1)
CT = CT.drop(['folio_str', 0], axis=1)

In [8]:
CT.columns = ['line_str', 'folio_num', 'side']
CT.folio_num = CT.folio_num.astype(int)

Remove unwanted things.

In [9]:
CT = CT.loc[~CT.line_str.str.match(r"Folio \d")].copy()
# CT.line_str = CT.line_str.str.replace(r"\d+", "", regex=True)
CT = CT[~CT.line_str.str.match("^\s*\d+\s*$")]
CT = CT[~(CT.line_str == '')]
CT = CT[~CT.line_str.str.match(r"^\s*$")]

In [10]:
CT

                                     line_str  folio_num   side
line_id
2                             ARE V XE OHER\n          1  recto
3                    Tzih varal Quiche vbi.\n          1  recto
4             Varal xchicatzibah vi xchica-\n          1  recto
5         tiquiba vi oher tzih, vticaribal,\n          1  recto
6               vxenabal puch ronohel xban,\n          1  recto
...                                       ...        ...    ...
5697          qoheic quiche ri rumal mahabi\n         56  verso
5698          chi ilbal re, qonabe oher cu-\n         56  verso
5699        mal ahauab zachinac chic.  xere\n         56  verso
5700      curi mi xutzinic chi conohel qui-\n         56  verso
5701                     che Sta. Cruz vbi.\n         56  verso

[5257 rows x 3 columns]

Add LB numbers.

In [11]:
CT['lb_num'] = 0
folio_num = ''
side = ''
lb_num = 0
for idx, row in CT.iterrows():
    if row['folio_num'] != folio_num:
        folio_num = row['folio_num']
    if row['side'] != side:
        side = row['side']
        lb_num = 0
    lb_num += 1
    CT.loc[idx, 'lb_num'] = lb_num

Identify paragrapghs by indent.

In [12]:
para_pat = "^    " # 4 space indent
CT.loc[CT.line_str.str.match(para_pat), 'para_num'] = 1
CT.loc[CT.line_str.str.match(para_pat), 'para_num'] = np.array(range((CT.para_num == 1).sum())) + 1
CT.para_num = CT.para_num.ffill()
CT.para_num = CT.para_num.fillna(0)
CT.para_num = CT.para_num.astype(int)

Create OHCO index.

In [13]:
CT = CT.reset_index(drop=True).set_index(OHCO)

Remove editorial numbers.

In [14]:
CT.line_str = CT.line_str.str.replace(r"\d+(\w)", r"\1", regex=True).str.replace(r"(\w)\d+", r"\1", regex=True)

In [15]:
CT[CT.line_str.str.match(r"^\d")]

                                                            line_str
folio_num side  lb_num para_num
56        recto 26     97          1  Ahau εalel vnabe ahau chuva-\n
                28     98        2  Ahau ah tzic vinac hun vnim ha\n
                29     98          3  Ahau εalel camha hun vnim ha\n
                30     98                4  Nima camha hun vnim ha\n
                31     98              5  Vchuch camha hun vnim ha\n
                32     98               6  Nima camha hun vnim ha.\n
                33     98         7  Nim chocoh nihaib hun vnim ha\n
                34     98              8  Ahau auilix hun vnim ha.\n
                35     98                9  Yacolatam hun vnim ha.\n

# Parse PARAs

In [16]:
PARA = CT.groupby(['para_num']).line_str.apply(" ".join).to_frame('doc_str')

Removed hyphens, etc.

In [17]:
PARA.doc_str = PARA.doc_str\
    .str.replace(r"-\n ", "", regex=True)\
    .str.replace(r"\n", "", regex=True)\
    .str.replace(r"\s+", " ", regex=True)\
    .str.strip()

In [18]:
PARA['n_chars'] = PARA.doc_str.str.len()

# Parse SENTs

In [19]:
SENT = PARA.doc_str.str.split(".")\
    .apply(pd.Series).stack().to_frame('sent_str')
SENT.sent_str = SENT.sent_str.str.strip()
SENT.index.names = ['para_num','sent_num']

In [20]:
# SENT.sample(10).sent_str.values

# Parse TOKENs

In [21]:
TOKEN = SENT.sent_str.str.split()\
    .apply(pd.Series).stack().to_frame('token_str')
TOKEN.index.names = ['para_num','sent_num','token_num']

In [22]:
TOKEN['term_str'] = TOKEN.token_str.str.lower()\
    .str.replace(",", "", regex=True)\
    .str.replace("[", "", regex=True)\
    .str.replace("(", "", regex=True)\
    .str.strip()

In [23]:
TOKEN

                            token_str term_str
para_num sent_num token_num
0        0        0               ARE      are
                  1                 V        v
                  2                XE       xe
                  3              OHER     oher
1        0        0              Tzih     tzih
...                               ...      ...
108      3        5           conohel  conohel
                  6            quiche   quiche
                  7               Sta      sta
         4        0              Cruz     cruz
                  1               vbi      vbi

[26904 rows x 2 columns]

# Extract VOCAB

In [24]:
VOCAB = TOKEN.term_str.value_counts().to_frame('n')
VOCAB.index.name = 'term_str'

In [25]:
VOCAB['p'] = VOCAB.n / VOCAB.n.sum()
VOCAB['i'] = np.log2(1/VOCAB.p)
VOCAB['h'] = VOCAB.p * VOCAB.i

In [26]:
VOCAB.head(20)

            n         p         i         h
term_str
ri        928  0.034493  4.857552  0.167552
ta        842  0.031296  4.997857  0.156415
cut       733  0.027245  5.197864  0.141616
qui       703  0.026130  5.258152  0.137395
chi       478  0.017767  5.814666  0.103308
vi        429  0.015946  5.970699  0.095206
xa        428  0.015908  5.974066  0.095038
hun       372  0.013827  6.176374  0.085400
are       350  0.013009  6.264322  0.081494
chic      343  0.012749  6.293468  0.080236
e         236  0.008772  6.832890  0.059938
v         220  0.008177  6.934173  0.056702
cu        209  0.007768  7.008174  0.054442
puch      208  0.007731  7.015093  0.054235
rumal     200  0.007434  7.071677  0.052570
cate      178  0.006616  7.239800  0.047899
balam     175  0.006505  7.264322  0.047252
xeqha     169  0.006282  7.314654  0.045948
vbi       166  0.006170  7.340494  0.045291
maui      158  0.005873  7.411752  0.043527

# Create BOW

In [27]:
BOW = TOKEN.groupby(["para_num", "term_str"]).term_str.count().unstack(fill_value=0)

In [28]:
BOW

term_str  0  1  2  3  4  5  6  7  8  9  a  abah  abanel  abanoh  abi  abix  \
para_num
0         0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
1         0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
2         0  0  0  0  0  0  0  0  0  0  0     0       1       0    0     0
3         0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
4         0  0  0  0  0  0  0  0  0  0  0     1       0       0    0     0
...      .. .. .. .. .. .. .. .. .. .. ..   ...     ...     ...  ...   ...
104       0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
105       0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
106       0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
107       0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0
108       0  0  0  0  0  0  0  0  0  0  0     0       0       0    0     0

term_str  abixic  abixom  ac  aca  acaab  acab  acaba  acabal  acah  acahau  \
para_num
0              0       0   0    0      0     0      0       0     0       0
1              0       0   0    0      0     0      0       0     0       0
2              0       0   0    0      0     0      0       0     0       0
3              0       0   0    0      0     0      0       0     0       0
4              0       0   0    0      0     0      0       0     0       0
...          ...     ...  ..  ...    ...   ...    ...     ...   ...     ...
104            0       0   0    0      0     0      0       0     0       0
105            0       0   0    0      0     0      0       0     0       0
106            0       0   0    0      0     0      0       0     0       0
107            0       0   0    0      0     0      0       0     0       0
108            0       0   0    0      0     0      0       0     0       0

term_str  acalab  acam  acan  acanic  acanoc  acaroc  acarroc  acavitz  ach  \
para_num
0              0     0     0       0       0       0        0        0    0
1              0     0     0       0       0       0        0        0    0
2              0     0     0       0       0       0        0        0    0
3              0     0     0       0       0       0        0        0    0
4              0     0     0       0       0       0        0        0    0
...          ...   ...   ...     ...     ...     ...      ...      ...  ...
104            0     0     0       0       0       0        0        0    0
105            0     0     0       0       0       0        0        0    0
106            0     0     0       0       0       0        0        0    0
107            0     0     0       0       0       0        0        0    0
108            0     0     0       0       0       0        0        0    0

term_str  achac  achbilai  achbilan  achih  achihab  achihal  achihil  \
para_num
0             0         0         0      0        0        0        0
1             0         0         0      0        0        0        0
2             0         0         0      0        0        0        0
3             0         0         0      0        0        0        0
4             0         0         0      0        0        0        0
...         ...       ...       ...    ...      ...      ...      ...
104           0         0         0      0        0        0        0
105           0         0         0      0        0        0        0
106           0         0         0      0        0        0        0
107           0         0         0      0        0        0        0
108           0         0         0      0        0        0        0

term_str  achihilal  achinac  achuch  acuil  acul  ah  aha  ahache  ahal  \
para_num
0                 0        0       0      0     0   0    0       0     0
1                 0        0       0      0     0   0    0       0     0
2                 0        0       0      0     0   2    0       0     0
3                 0        0       0      0     0   0    0       0     0
4                 0        0       0      0     0   0    0       0     0
...             ...      ...     ...    ...   ...  ..  ...     ...   ...
104               0        0       0      0     0   0    0       0     0
105               0        0       0      0     0   0    0       0     0
106               0        0       0      0     0   0    0       0     0
107               0        0       0      0     0   0    0       0     0
108               0        0       0      0     0   0    0       0     0

term_str  ahalcana  ahalmez  ahalpuh  ahaltocob  aham  ahamche  ahau  ahauab  \
para_num
0                0        0        0          0     0        0     0       0
1                0        0        0          0     0        0     0       0
2                0        0        0          0     0        0     0       0
3                0        0        0          0     0        0     0       0
4                0        0        0          0     0        0     0       0
...            ...      ...      ...        ...   ...      ...   ...     ...
104              0        0        0          0     0        0     1       0
105              0        0        0          0     0        0     0       0
106              0        0        0          0     0        0     1       0
107              0        0        0          0     0        0     0       0
108              0        0        0          0     0        0     2       1

term_str  ahaual  ahauar  ahauarem  ahavab  ahavah  ahbatena  ahbit  ahbix  \
para_num
0              0       0         0       0       0         0      0      0
1              0       0         0       0       0         0      0      0
2              0       0         0       0       0         0      0      0
3              0       0         0       0       0         0      0      0
4              0       0         0       0       0         0      0      0
...          ...     ...       ...     ...     ...       ...    ...    ...
104            0       0         0       0       0         0      0      0
105            0       0         0       0       0         0      0      0
106            0       0         0       0       0         0      0      0
107            0       0         0       1       0         0      0      0
108            0       0         0       0       0         0      0      0

term_str  ahbiz  ahcab  ahcah  ahcahb  ahcahb:  ahchoc  ahchoce  ahcot  ahe  \
para_num
0             0      0      0       0        0       0        0      0    0
1             0      0      0       0        0       0        0      0    0
2             1      0      0       0        0       0        0      0    0
3             0      0      0       0        0       0        0      0    0
4             0      0      0       0        0       0        0      0    0
...         ...    ...    ...     ...      ...     ...      ...    ...  ...
104           0      0      0       0        0       0        0      0    0
105           0      0      0       0        0       0        0      0    0
106           0      0      0       0        0       0        0      0    0
107           0      0      0       0        0       0        0      0    0
108           0      0      0       0        0       0        0      0    0

term_str  ahi  ahilam  ahilan  ahilatal  ahlabal  ahloε  ahmac  ahnaoh  ahnim  \
para_num
0           0       0       0         0        0      0      0       0      0
1           0       0       0         0        0      0      0       0      0
2           0       0       0         0        0      0      0       1      0
3           0       0       0         0        0      0      0       0      0
4           0       0       0         0        0      0      0       1      0
...       ...     ...     ...       ...      ...    ...    ...     ...    ...
104         0       0       0         0        0      0      0       0      0
105         0       0       0         0        0      0      0       0      0
106         0       0       0         0        0      0      0       0      0
107         0       0       0         0        0      0      0       0      0
108         0       0       0         0        0      0      0       0      0

term_str  ahoxbal  ahpatan  ahpop  ahpopcam  ahpopcamha  ahpopol  ahpu  \
para_num
0               0        0      0         0           0        0     0
1               0        0      0         0           0        0     0
2               0        0      0         0           0        0     2
3               0        0      0         0           0        0     0
4               0        0      0         0           0        0     0
...           ...      ...    ...       ...         ...      ...   ...
104             0        0      0         0           0        0     0
105             0        0      0         0           0        0     0
106             0        0      0         0           0        0     0
107             0        0      0         0           0        0     0
108             0        0      0         0           0        0     0

term_str  ahqiquina  ahqiquinaha  ahquibaha  ahquih  ahquix  ahquixb  ahqun  \
para_num
0                 0            0          0       0       0        0      0
1                 0            0          0       0       0        0      0
2                 0            0          0       0       0        0      0
3                 0            0          0       0       0        0      0
4                 0            0          0       0       0        0      0
...             ...          ...        ...     ...     ...      ...    ...
104               0            0          0       0       0        0      0
105               0            0          0       0       0        0      0
106               0            0          0       0       0        0      0
107               0            0          0       0       0        0      0
108               0            0          0       0       0        0      0

term_str  ahrelebal  ahtinamit  ahtzac  ahtzibenai  ahtzic  ahuchan  ahvqhan  \
para_num
0                 0          0       0           0       0        0        0
1                 0          0       0           0       0        0        0
2                 0          0       0           0       0        0        0
3                 0          0       0           0       0        0        0
4                 0          0       0           0       0        0        0
...             ...        ...     ...         ...     ...      ...      ...
104               0          0       0           0       0        0        0
105               0          0       0           0       0        0        0
106               0          0       0           0       0        0        0
107               0          0       0           0       0        0        0
108               0          0       0           0       0        0        0

term_str  ahxayabah  ahxob  ahzib  ahzibab  ahzic  ahzivan  ahzu  al  ala  \
para_num
0                 0      0      0        0      0        0     0   0    0
1                 0      0      0        0      0        0     0   0    0
2                 0      0      0        0      0        0     0   1    0
3                 0      0      0        0      0        0     0   0    0
4                 0      0      0        0      0        0     0   0    0
...             ...    ...    ...      ...    ...      ...   ...  ..  ...
104               0      0      0        0      0        0     0   0    0
105               0      0      0        0      0        0     0   0    0
106               0      0      0        0      0        0     0   0    0
107               0      0      0        0      0        0     0   0    0
108               0      0      0        0      0        0     0   0    0

term_str  alaba  alabilaxic  alac  alachinac  alai  alal  alanel  alay  \
para_num
0             0           0     0          0     0     0       0     0
1             0           0     0          0     0     0       0     0
2             0           0     0          0     0     0       0     1
3             0           0     0          0     0     0       0     0
4             0           0     0          0     0     0       0     0
...         ...         ...   ...        ...   ...   ...     ...   ...
104           0           0     0          0     0     0       0     0
105           0           0     0          0     0     0       0     0
106           0           0     0          0     0     0       0     0
107           0           0     0          0     0     0       1     0
108           0           0     0          0     0     0       0     0

term_str  alcual  alib  alibla  alom  alubic  ama  amac  amactan  amaquel  \
para_num
0              0     0       0     0       0    0     0        0        0
1              0     0       0     0       0    0     0        0        0
2              0     0       0     1       0    0     0        0        0
3              0     0       0     0       0    0     0        0        0
4              0     0       0     1       0    0     0        0        0
...          ...   ...     ...   ...     ...  ...   ...      ...      ...
104            0     0       0     0       0    0     0        0        0
105            0     0       0     0       0    0     0        0        0
106            0     0       0     0       0    0     0        0        0
107            0     0       0     0       0    0     0        0        0
108            0     0       0     0       0    0     0        0        0

term_str  amaquelab  amaquil  anam  anavi  anilabic  anim  anom  aon  apa  \
para_num
0                 0        0     0      0         0     0     0    0    0
1                 0        0     0      0         0     0     0    0    0
2                 0        1     0      0         0     0     0    0    0
3                 0        0     0      0         0     0     0    0    0
4                 0        0     0      0         0     0     0    0    0
...             ...      ...   ...    ...       ...   ...   ...  ...  ...
104               0        0     0      0         0     0     0    0    0
105               0        0     0      0         0     0     0    0    0
106               0        0     0      0         0     0     0    0    0
107               0        0     0      0         0     0     0    0    0
108               0        0     0      0         0     0     0    0    0

term_str  apachina  apachinac  apan  apanoc  apetic  apon  aponoc  aqui  aqux  \
para_num
0                0          0     0       0       0     0       0     0     0
1                0          0     0       0       0     0       0     0     0
2                0          0     0       0       0     0       0     0     0
3                0          0     0       0       0     0       0     0     0
4                0          0     0       0       0     0       0     0     0
...            ...        ...   ...     ...     ...   ...     ...   ...   ...
104              0          0     0       0       0     0       0     0     0
105              0          0     0       0       0     0       0     0     0
106              0          0     0       0       0     0       0     0     0
107              0          0     0       0       0     0       0     0     0
108              0          0     0       0       0     0       0     0     0

term_str  araroc  araxal  are  areba  arecut  arepu  arepuch  areri  areta  \
para_num
0              0       0    1      0       0      0        0      0      0
1              0       0    0      0       0      0        0      0      0
2              0       0    0      0       1      0        0      0      0
3              0       0    1      0       0      0        0      0      0
4              0       0    2      0       0      0        0      0      0
...          ...     ...  ...    ...     ...    ...      ...    ...    ...
104            0       0    0      0       0      0        0      0      0
105            0       0    0      0       0      0        0      0      0
106            0       0    0      0       0      0        0      0      0
107            0       0    1      0       0      0        0      0      0
108            0       0    0      0       0      0        0      0      0

term_str  at  ata  ataca  atala  atalabe  atan  ate  atin  atit  ato  atoob  \
para_num
0          0    0      0      0        0     0    0     0     0    0      0
1          0    0      0      0        0     0    0     0     0    0      0
2          0    0      0      0        0     0    0     0     0    1      0
3          0    0      0      0        0     0    0     0     0    0      0
4          0    0      0      0        0     0    0     0     0    0      0
...       ..  ...    ...    ...      ...   ...  ...   ...   ...  ...    ...
104        0    0      0      0        0     0    0     0     0    0      0
105        0    0      0      0        0     0    0     0     0    0      0
106        0    0      0      0        0     0    0     0     0    0      0
107        0    0      0      0        0     0    0     0     0    0      0
108        0    0      0      0        0     0    0     0     0    0      0

term_str  atzaca  atziac  atzih  atziiac  atziyac  au  auazinic  aue  auech  \
para_num
0              0       0      0        0        0   0         0    0      0
1              0       0      0        0        0   0         0    0      0
2              0       0      0        0        0   0         0    0      0
3              0       0      0        0        0   0         0    0      0
4              0       0      0        0        0   0         0    0      0
...          ...     ...    ...      ...      ...  ..       ...  ...    ...
104            0       0      0        0        0   0         0    0      0
105            0       0      0        0        0   0         0    0      0
106            0       0      0        0        0   0         0    0      0
107            0       0      0        0        0   0         0    0      0
108            0       0      0        0        0   0         0    0      0

term_str  auetaam  auib  auilix  auiquicab  aulix  auvmal  aval  ave  ave;  \
para_num
0               0     0       0          0      0       0     0    0     0
1               0     0       0          0      0       0     0    0     0
2               0     0       0          0      0       0     0    0     0
3               0     0       0          0      0       0     0    0     0
4               0     0       0          0      0       0     0    0     0
...           ...   ...     ...        ...    ...     ...   ...  ...   ...
104             0     0       0          0      0       0     0    0     0
105             0     0       0          0      0       0     0    0     0
106             0     0       0          0      0       0     0    0     0
107             0     0       0          0      0       0     0    0     0
108             0     0       0          0      0       0     0    0     0

term_str  avech  avecha  avi  avila  avilix  avion  avitzmal  avlix  avmal  \
para_num
0             0       0    0      0       0      0         0      0      0
1             0       0    0      0       0      0         0      0      0
2             0       0    0      0       0      0         0      0      0
3             0       0    0      0       0      0         0      0      0
4             0       0    0      0       0      0         0      0      0
...         ...     ...  ...    ...     ...    ...       ...    ...    ...
104           0       0    0      0       0      0         0      0      0
105           0       0    0      0       0      0         0      0      0
106           0       0    0      0       0      0         0      0      0
107           0       0    0      0       0      0         0      0      0

# Compute TFIDF

In [29]:
N_docs = len(BOW)
VOCAB['df'] = BOW.astype(bool).sum()
VOCAB['idf'] = np.log2(N_docs/VOCAB.df)
VOCAB['dfidf'] = VOCAB.df * VOCAB.idf

In [30]:
# VOCAB['dp'] = VOCAB.df / VOCAB.df.sum()
VOCAB['dp'] = VOCAB.df / N_docs
VOCAB['di'] = np.log2(1/VOCAB.dp)
VOCAB['dh'] = VOCAB.dp * VOCAB.di

In [31]:
TFIDF = BOW * VOCAB.idf

In [32]:
VOCAB['tfidf_mean'] = TFIDF.mean()

In [33]:
VOCAB.sort_values('dfidf', ascending=False).head(10).style.background_gradient(cmap="YlGnBu")

In [34]:
VOCAB[VOCAB.dh > .5].sort_values('dh', ascending=False)

,n,p,i,h,df,idf,dfidf,dp,di,dh,tfidf_mean
term_str,,,,,,,,,,,
nim,62,0.002304,8.761337,0.020190,40,1.446256,57.850249,0.366972,1.446256,0.530736,0.822641
ahau,133,0.004944,7.660251,0.037868,40,1.446256,57.850249,0.366972,1.446256,0.530736,1.764698
mi,152,0.005650,7.467606,0.042190,41,1.410632,57.835925,0.376147,1.410632,0.530605,1.967120
quih,111,0.004126,7.921117,0.032681,39,1.482782,57.828502,0.357798,1.482782,0.530537,1.509989
chiri,121,0.004497,7.796670,0.035065,39,1.482782,57.828502,0.357798,1.482782,0.530537,1.646024
vloc,110,0.004089,7.934173,0.032440,39,1.482782,57.828502,0.357798,1.482782,0.530537,1.496386
que,79,0.002936,8.411752,0.024700,42,1.375867,57.786410,0.385321,1.375867,0.530151,0.997188
curi,128,0.004758,7.715533,0.036708,42,1.375867,57.786410,0.385321,1.375867,0.530151,1.615697
chire,87,0.003234,8.272590,0.026751,42,1.375867,57.786410,0.385321,1.375867,0.530151,1.098169
chicut,95,0.003531,8.145677,0.028763,42,1.375867,57.786410,0.385321,1.375867,0.530151,1.199150
na,74,0.002751,8.506080,0.023396,38,1.520257,57.769759,0.348624,1.520257,0.529998,1.032101
ruq,88,0.003271,8.256101,0.027005,38,1.520257,57.769759,0.348624,1.520257,0.529998,1.227363
ha,89,0.003308,8.239800,0.027258,43,1.341920,57.702542,0.394495,1.341920,0.529381,1.095696
quitzih,90,0.003345,8.223680,0.027510,37,1.558731,57.673045,0.339450,1.558731,0.529111,1.287026
chuvi,76,0.002825,8.467606,0.023920,37,1.558731,57.673045,0.339450,1.558731,0.529111,1.086822
quib,102,0.003791,8.043108,0.030493,45,1.276331,57.434905,0.412844,1.276331,0.526926,1.194365
pa,149,0.005538,7.496365,0.041516,45,1.276331,57.434905,0.412844,1.276331,0.526926,1.744710
xqha,125,0.004646,7.749749,0.036006,35,1.638901,57.361546,0.321101,1.638901,0.526253,1.879474
mahabi,73,0.002713,8.525709,0.023133,35,1.638901,57.361546,0.321101,1.638901,0.526253,1.097613
pu,109,0.004051,7.947349,0.032198,46,1.244622,57.252629,0.422018,1.244622,0.525253,1.244622
nabe,73,0.002713,8.525709,0.023133,46,1.244622,57.252629,0.422018,1.244622,0.525253,0.833554
va,80,0.002974,8.393605,0.024959,46,1.244622,57.252629,0.422018,1.244622,0.525253,0.913484
ma,51,0.001896,9.043108,0.017142,34,1.680721,57.144530,0.311927,1.680721,0.524262,0.786393
chique,63,0.002342,8.738253,0.020462,34,1.680721,57.144530,0.311927,1.680721,0.524262,0.971426
qo,119,0.004423,7.820715,0.034592,47,1.213595,57.038987,0.431193,1.213595,0.523293,1.324935
chuvach,95,0.003531,8.145677,0.028763,47,1.213595,57.038987,0.431193,1.213595,0.523293,1.057721
xe,121,0.004497,7.796670,0.035065,47,1.213595,57.038987,0.431193,1.213595,0.523293,1.347202
cumal,94,0.003494,8.160944,0.028514,47,1.213595,57.038987,0.431193,1.213595,0.523293,1.046587
qux,73,0.002713,8.525709,0.023133,33,1.723790,56.885077,0.302752,1.723790,0.521881,1.154465
nima,74,0.002751,8.506080,0.023396,33,1.723790,56.885077,0.302752,1.723790,0.521881,1.170280
xeqha,169,0.006282,7.314654,0.045948,48,1.183222,56.794648,0.440367,1.183222,0.521052,1.834537
vtz,73,0.002713,8.525709,0.023133,32,1.768184,56.581898,0.293578,1.768184,0.519100,1.184197
ahauab,115,0.004274,7.870043,0.033640,32,1.768184,56.581898,0.293578,1.768184,0.519100,1.865516
huyub,86,0.003197,8.289268,0.026497,32,1.768184,56.581898,0.293578,1.768184,0.519100,1.395081
xavi,71,0.002639,8.565786,0.022605,32,1.768184,56.581898,0.293578,1.768184,0.519100,1.151753
ronohel,123,0.004572,7.773019,0.035537,49,1.153474,56.520250,0.449541,1.153474,0.518534,1.301627
ca,122,0.004535,7.784796,0.035301,49,1.153474,56.520250,0.449541,1.153474,0.518534,1.291045
balam,175,0.006505,7.264322,0.047252,31,1.813988,56.233628,0.284404,1.813988,0.515905,2.912366
vach,119,0.004423,7.820715,0.034592,50,1.124328,56.216407,0.458716,1.124328,0.515747,1.227478
quehe,101,0.003754,8.057322,0.030248,50,1.124328,56.216407,0.458716,1.124328,0.515747,1.041809
cate,178,0.006616,7.239800,0.047899,51,1.095759,55.883708,0.467890,1.095759,0.512695,1.789405
vinac,147,0.005464,7.515861,0.041066,51,1.095759,55.883708,0.467890,1.095759,0.512695,1.477767
conohel,67,0.002490,8.649444,0.021540,30,1.861294,55.838812,0.275229,1.861294,0.512283,1.144098
xere,59,0.002193,8.832890,0.019370,30,1.861294,55.838812,0.275229,1.861294,0.512283,1.007489
a,49,0.001821,9.100823,0.016575,30,1.861294,55.838812,0.275229,1.861294,0.512283,0.836728
vleu,59,0.002193,8.832890,0.019370,29,1.910203,55.395897,0.266055,1.910203,0.508219,1.033963
xuxic,47,0.001747,9.160944,0.016004,28,1.960829,54.903223,0.256881,1.960829,0.503699,0.845495
re,47,0.001747,9.160944,0.016004,28,1.960829,54.903223,0.256881,1.960829,0.503699,0.845495
macu,47,0.001747,9.160944,0.016004,28,1.960829,54.903223,0.256881,1.960829,0.503699,0.845495
vbi,166,0.006170,7.340494,0.045291,54,1.013297,54.718028,0.495413,1.013297,0.502000,1.543186

In [35]:
VOCAB.loc[(VOCAB.dh > .3 ) & (VOCAB.tfidf_mean < 2.1)].sort_index()

,n,p,i,h,df,idf,dfidf,dp,di,dh,tfidf_mean
term_str,,,,,,,,,,,
a,49,0.001821,9.100823,0.016575,30,1.861294,55.838812,0.275229,1.861294,0.512283,0.836728
abah,27,0.001004,9.960646,0.009996,17,2.680721,45.572265,0.155963,2.680721,0.418094,0.664032
acab,59,0.002193,8.832890,0.019370,24,2.183222,52.397324,0.220183,2.183222,0.480709,1.181744
ah,95,0.003531,8.145677,0.028763,25,2.124328,53.108203,0.229358,2.124328,0.487231,1.851479
ahau,133,0.004944,7.660251,0.037868,40,1.446256,57.850249,0.366972,1.446256,0.530736,1.764698
...,...,...,...,...,...,...,...,...,...,...,...
ya,14,0.000520,10.908178,0.005676,10,3.446256,34.462562,0.091743,3.446256,0.316170,0.442638
zac,26,0.000966,10.015093,0.009679,19,2.520257,47.884879,0.174312,2.520257,0.439311,0.601162
zcaquin,19,0.000706,10.467606,0.007392,15,2.861294,42.919406,0.137615,2.861294,0.393756,0.498758
zivan,22,0.000818,10.256101,0.008387,14,2.960829,41.451612,0.128440,2.960829,0.380290,0.597599
εaε,38,0.001412,9.467606,0.013372,12,3.183222,38.198662,0.110092,3.183222,0.350446,1.109747

In [36]:
CHAR = pd.DataFrame([list(w) for w in VOCAB.index]).stack().value_counts().to_frame('n')

In [37]:
CHAR.sort_index()

      n
)     1
-    10
0     1
1     1
2     2
3     1
4     1
5     1
6     1
7     1
8     1
9     1
:    10
;    19
?     8
]     1
a  4947
b  1062
c  4373
d     9
e  1438
g     1
h  3152
i  3900
j     2
k     1
l  1448
m   797
n  1143
o  1689
p   457
q  1414
r   481
s    15
t  1239
u  2745
v   811
w     1
x  1774
y   211
z   747
~     1
º     1
ï     1
ÿ    52
ε    91
’     1

# About $ε$

> The letter "ε" in the K'iche' language is pronounced by closing the throat and forcefully expelling air while keeping the tongue in the same position as for the letter "q". This produces a glottalized "q" sound.

Same as $q'$?

# Save

In [38]:
CT.to_csv("christenson-quiche-LINES.csv", index=True)

In [39]:
PARA.to_csv("christenson-quiche-PARA.csv", index=True)

In [40]:
TFIDF.to_csv("christenson-quiche-TFIDF.csv", index=True)