# Christenson Chapter Titles

Note: Christenson misnumbers lines in his literal translation:

- The line marked $4910$ on page $170$ is actually line $4908$, leaving $8$ lines in one group and $12$ in the next.
- Line $5250$ repeated twice on page $182$, throwing off the rest by $10$. This means the total number of lines in the text is $8726$, not $8716$.

Therefore, the `xom-` lines below need to be corrected if we want to map to source.

In [11]:
import pandas as pd
import numpy as np

In [12]:
titles = pd.read_csv("christenson-pv-titles.csv", sep="|")
titles.index.name = 'chap_num'
titles.index += 1

In [13]:
xom_lines = pd.read_csv("christenson-pv-english-xom-lines.csv").set_index('chap_num')

In [14]:
CHAP = titles.join(xom_lines)

In [15]:
CHAP

                                               chap_title  page_num  xom_lines
chap_num
1                                                Preamble        59       1-96
2                                    The Primordial World        67     97-154
3                               The Creation of the Earth        70    155-274
4                             The Creation of the Animals        74    275-339
5                                 The Fall of the Animals        76    340-433
...                                                   ...       ...        ...
83                            The Dynasty of Nihaib Lords       301  8596-8631
84                   The Great Houses of the Nihaib Lords       302  8632-8663
85                       The Dynasty of Ahau Quiché Lords       303  8664-8679
86              The Great Houses of the Ahau Quiché Lords       304  8680-8695
87        The Three Great Stewards as Mothers of the Word       305  8696-8716

[87 rows x 3 columns]

In [16]:
if 'xom_start' not in CHAP.columns:
    CHAP = CHAP.join(CHAP.xom_lines.str.split('-').apply(pd.Series).rename(columns={0:'xom_start',1:'xom_end'}))
    CHAP.xom_start = CHAP.xom_start.astype(int)
    CHAP.xom_end = CHAP.xom_end.astype(int)
    CHAP = CHAP.drop('xom_lines', axis=1)

In [17]:
CHAP

,chap_title,page_num,xom_start,xom_end
chap_num,,,,
1,Preamble,59,1,96
2,The Primordial World,67,97,154
3,The Creation of the Earth,70,155,274
4,The Creation of the Animals,74,275,339
5,The Fall of the Animals,76,340,433
...,...,...,...,...
83,The Dynasty of Nihaib Lords,301,8596,8631
84,The Great Houses of the Nihaib Lords,302,8632,8663
85,The Dynasty of Ahau Quiché Lords,303,8664,8679
86,The Great Houses of the Ahau Quiché Lords,304,8680,8695
87,The Three Great Stewards as Mothers of the Word,305,8696,8716

In [20]:
CHAP[CHAP.xom_start > 4900]

,chap_title,page_num,xom_start,xom_end
chap_num,,,,
43,The First Four Men,196,4940,4947
44,The Miraculous Vision of the First Men,197,4948,5010
45,The Gratitude of the First Men,199,5011,5071
46,The Displeasure of the Gods,200,5072,5115
47,The Creation of the Mothers of the Quiché Nation,201,5116,5360
48,The Arrival at Tulan,209,5361,5374
49,The Progenitors Receive their Gods,211,5375,5413
50,The Progenitors Leave Tulan,213,5414,5485
51,The Nations Ask for their Fire,214,5486,5601
52,The Nations Are Deceived into Offering Themselves,216,5602,5774
53,The People Gather on the Mountain Chi Pixab,220,5775,5796
54,Their Suffering on the Mountain Chi Pixab,221,5797,5870
55,The Progenitors Await the First Dawn,223,5871,6043
56,The Appearance of the First Dawn,228,6044,6289
57,Offerings Are Made to the Gods,233,6290,6503
58,The Sacrificial Killings Begin,238,6504,6597
59,The Nations Plot to Seduce the Gods,240,6598,6699
60,The Seduction of Lady Lust and Lady Wailing,242,6700,6775
61,The Nations Are Defeated by the Painted Robes,245,6776,6919
62,The Nations Are Humiliated,248,6920,7075
63,The Nations Are Defeated,251,7076,7206
64,The Deaths of the Four Progenitors,253,7207,7360
65,The Sons of the Progenitors Journey to Tulan,255,7361,7411
66,The Sons Receive Authority to Rule,257,7412,7450
67,The Migrations of the Quichés,260,7451,7550
68,The Foundation of Chi Izmachi,262,7550,7707
69,The Foundation of Cumarcah,266,7708,7787
70,The Titles of the Cavec Lords,269,7788,7802
71,The Titles of the Nihaib Lords,271,7803,7814
72,The Titles of the Ahau Quiché Lords,272,7815,7822
73,The Titles of the Zaquic Lords,273,7823,7828
74,The Glory of the Lords of Cumarcah,274,7829,7943
75,The Victories of Lord Quicab,277,7944,8032
76,The Quichés Garrison the Conquered Regions,281,8033,8180
77,The Titles Given to Those Who Were Ennobled,284,8181,8231
78,The Names of the Gods’ Houses,285,8232,8325
79,The Prayer of the Lords to their Gods,289,8326,8490
80,The Generations of Quiché Lords,292,8491,8515
81,The Dynasty of Cavec Quiché Lords,293,8516,8555
82,The Great Houses of the Cavec Lords,299,8556,8595
83,The Dynasty of Nihaib Lords,301,8596,8631
84,The Great Houses of the Nihaib Lords,302,8632,8663
85,The Dynasty of Ahau Quiché Lords,303,8664,8679
86,The Great Houses of the Ahau Quiché Lords,304,8680,8695
87,The Three Great Stewards as Mothers of the Word,305,8696,8716

In [18]:
CHAP.to_csv("christenson-CHAP.csv", index=True)