# Christenson Extract Lines from Literal

Actual number of lines = $8726$.

Christenson misnumbers lines:
- $4910$ is at $4908$.
- $5260$ repeated twice, throwing off the rest.

**NOW FIXED.**

In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [2]:
lines = pd.DataFrame(open("christenson-pv-literal.txt", "r").readlines(), columns=['line_str'])
lines = lines[~lines.line_str.str.match(r"^#")]
lines.line_str = lines.line_str.str.strip()
page_num_pat = r"\s*\d+\s*$"
lines['page_num'] = lines[lines.line_str.str.match(page_num_pat)].line_str
lines.page_num = lines.page_num.bfill()
lines = lines[~lines.line_str.str.match(page_num_pat)].copy()
lines = lines.dropna()
lines = lines[~lines.line_str.str.match(r"^\s*$")]
lines = lines.reset_index(drop=True)
lines.index = lines.index + 1
lines.index.name = 'line_num'

In [3]:
LINE = lines.line_str.str.split(r"\s\s+").apply(pd.Series).rename(columns={0:'eng_str', 1:'quc_str', 2:'line_marker'})
LINE.line_marker = LINE.line_marker.fillna('')
LINE.eng_str = LINE.eng_str.str.replace(r"\d+", "", regex=True)
LINE.quc_str = LINE.quc_str.str.replace(r"\d+", "", regex=True)

In [4]:
LINE.head(10)

,eng_str,quc_str,line_marker
line_num,,,
1,"THIS ITS ROOT ANCIENT WORD,","ARE' U XE' OJER TZIJ,",
2,Here Quiché its name.,Waral K'iche' u b'i'.,
3,"HERE we shall write,","WARAL xchiqatz'ib'aj wi,",
4,"We shall plant ancient word,","Xchiqatikib'a' wi ojer tzij,",
5,"Its planting,","U tikarib'al,",
6,"Its root-beginning as well,","U xe'nab'al puch,",
7,Everything done in,Ronojel xb'an pa,
8,"Citadel Quiché,","Tinamit K'iche',",
9,Its nation Quiché people.,Ramaq' K'iche' winaq.,
10,This therefore we shall gather,Are' k'ut xchiqak'am wi,10

In [7]:
LINE

,eng_str,quc_str,line_marker
line_num,,,
1,"THIS ITS ROOT ANCIENT WORD,","ARE' U XE' OJER TZIJ,",
2,Here Quiché its name.,Waral K'iche' u b'i'.,
3,"HERE we shall write,","WARAL xchiqatz'ib'aj wi,",
4,"We shall plant ancient word,","Xchiqatikib'a' wi ojer tzij,",
5,"Its planting,","U tikarib'al,",
...,...,...,...
8722,This because not now means of sight of it.,Ri' rumal maja b'i chi ilb'al re.,
8723,There is first anciently by lords.,K'o nab'e ojer kumal ajawab'.,
8724,Lost now.,Sachinaq chik.,
8725,"But therefore this was completed now all Quiché,","Xere k'u ri' mi xutzinik chi konojel K'iche',",
8726,Sta. Cruz its name.,Sta. Cruz u b'i'.,

# Save

In [5]:
with open("christenson-pv-literal-processed.txt", "w") as outfile:
    outfile.write('\n'.join(lines.line_str.to_list()))

In [6]:
LINE.to_csv("christenson-LINE_LITERAL.csv", index=True)