In [2]:
import pandas as pd

In [1]:
!ls *CHUNK*

182.17s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

CHUNKMAP.csv                           colop-CHUNK-60.csv
ajtzibab-CHUNK-60.csv                  recinos-CHUNK-60.csv
christenson-CHUNK-60.csv               tedlock-CHUNK-60.csv
christenson_english_prose-CHUNK-60.csv ximenez-CHUNK-60.csv
christenson_ximenez-CHUNK-60.csv

In [24]:
n_chunks = 60
chunk_files = !ls *CHUNK-{n_chunks}*
chunk_str_dfs = []
chunk_doc_dfs = []
src_ids = []
for cf in chunk_files:
    src_id = cf.split('-')[0]
    src_ids.append(src_id)
    df = pd.read_csv(cf).set_index('chunk_num')
    chunk_str_dfs.append(df.chunk_str)
    chunk_doc_dfs.append(df.doc_id)

In [25]:
CHUNKSTR = pd.concat(chunk_str_dfs, axis=1, keys=src_ids)
CHUNKSTR.head()

,ajtzibab,christenson,christenson_english_prose,christenson_ximenez,colop,recinos,tedlock,ximenez
chunk_num,,,,,,,,
0,popol wuj ojer taq tzij xb'an pa tinamit k'ich...,are' u xe' ojer tzij waral k'iche' u b'i' wara...,this is the beginning of the ancient tradition...,are v xe oher tzih varal quiche vbi varal xchi...,are' uxe' ojer tzij waral k'iche' ub'i' waral ...,este es el principio de las antiguas historias...,this is the beginning of the ancient word here...,are v xe oher tzih varal quiche vbi varal xchi...
1,taj chijamataj chiwinaqir wa ulew ulaq'el ch'a...,ta chawaxoq ta saqiro puch apachinaq tzuqul q'...,to humanity then they arranged for the germina...,ha chel tah chihamatah chivinaquir va vleu vla...,kixnojin taj are ri ja' chel taj chi jama' taj...,los bejucos y el nacimiento de la vida y la cr...,was conceived how should it be sown how should...,hupacha ta cha uaxoc ta caquiro puch apachinac...
2,nimachikop k'o chuwach ulew ta xraj k'u kitij ...,k'ajolom xe'uchax k'ut xa kixjalatajik rumal m...,has borne children and he who has begotten son...,alom qaholom xevqhax cut xa quixhalatahic ruma...,mi k'u xqajal qatzij iwecha' ik'uxun iwarab'al...,gorjead llamad hablad cada uno segn vuestra es...,and begetters said among themselves so they to...,chic qui bil quib maui mixutzin v bixic cabi r...
3,b'it katk'ix la uloq at uk'u'x kaj maqajisaj u...,che' xe'uchaxik e aj q'ij k'ate puch u qajik u...,that will call upon us they asked then they th...,ixim chi tzite xa chibanatahic xa pu chel apan...,chi kech are ri mama' are ajtz'ite' xpiyakok u...,el hombre que formemos el hombre que vamos a c...,your hands over the kernels of corn over the s...,camul qaholom nimac nima tziz ah cuval ah yama...
4,ri kixk'ub' chitaninik chipe pa q'aq' tak'al c...,ta nab'e qa patan chiwach ix ta na winaq wakam...,they had no sweat or oil their cheeks were dry...,hu ta quih hu ta quih xquec zaquiric amaquel h...,mixojkamik iwumal jupa cha mawi mixixnawik xix...,anegados una resina abundante vino del cielo e...,stones each and every thing crushed their face...,che abah xqhauic ronohel qui quebalquixot qui ...

In [ ]:
CHUNKSTR.to_csv("CHUNKSTR.csv", index=True)

In [40]:
CHUNKDOC = pd.concat(chunk_doc_dfs, axis=1, keys=src_ids)
CHUNKDOC.columns.name = 'src_id'
CHUNKDOC.head()

src_id,ajtzibab,christenson,christenson_english_prose,christenson_ximenez,colop,recinos,tedlock,ximenez
chunk_num,,,,,,,,
0,0 1 2 3 4 5 6,1 2 3,1 2 3,0 1 2 3 4 5,1,0 1,1,1 2 3 4 5
1,6 7 8 9 10 11 12,3 4 5,3 4 5,5 6 7,1,1,1,5 6 7
2,12 13 14,5 6 7,5 6,7 8,1,1,1,7 8
3,14 15 16 17 18 19,7 8,6 7,8 9,1,1,1,8 9
4,19 20 21 22,8 9,7 8,9 10,1 2,1,1,9 10

In [83]:
# CHUNKSTR.colop

In [67]:
CHUNKDOC2 = CHUNKDOC.stack().to_frame('doc_ids').doc_ids.str.split(expand=True).stack().dropna().to_frame('doc_id')
CHUNKDOC2.index.names = ['chunk_num', 'src_id', 'doc_num']
CHUNKDOC2

                           doc_id
chunk_num src_id   doc_num
0         ajtzibab 0            0
                   1            1
                   2            2
                   3            3
                   4            4
...                           ...
59        ximenez  4           93
                   5           94
                   6           95
                   7           96
                   8           97

[1018 rows x 1 columns]

In [80]:
E = CHUNKDOC2.groupby('src_id')
E_colop = E.get_group('colop')
E_colop
# E_colop.doc_id.value_counts().sort_index()

                         doc_id
chunk_num src_id doc_num
0         colop  0            1
1         colop  0            1
2         colop  0            1
3         colop  0            1
4         colop  0            1
...                         ...
55        colop  0            5
56        colop  0            5
57        colop  0            5
58        colop  0            5
59        colop  0            5

[64 rows x 1 columns]

In [ ]:
# COLOP = pd.read_csv("../colop/colop-DOC.csv")

In [86]:
# COLOP