# Recinos Noun Phrases

In [ ]:
import pandas as pd
from unidecode import unidecode

In [ ]:
SPACY = pd.read_pickle("spacy.pickle")

In [49]:
NP = SPACY.apply(lambda x: ["".join(str(np)) for np in x.noun_chunks]).apply(pd.Series).stack().to_frame('np')

In [83]:
NP['np'] = NP.np.apply(unidecode).str.upper().str.replace("\W+", "", regex=True).str.strip()

In [84]:
NP.sort_values('np')

                        np
parte capit
4     11    240     ABEJAS
      2     377  ABEJORROS
2     6     317     ABUELA
            5       ABUELA
3     3     192     ABUELA
...                    ...
4     10    147     ZIYAHA
2     11    48    ZOPILOTE
      2     294    ZOTZIHA
3     6     5        ZOTZU
4     7     14      ZTAYUL

[9405 rows x 1 columns]

In [86]:
NPM = NP.groupby(['parte', 'capit', 'np']).np.count().unstack(fill_value=0)

In [92]:
DFIDF

np
ABEJAS            5.523562
ABEJORROS         5.523562
ABUELA           17.631597
ABUELANUESTRA     5.523562
ABUELO            9.047124
                   ...
ZIYAHA            5.523562
ZOPILOTE          5.523562
ZOTZIHA           5.523562
ZOTZU             5.523562
ZTAYUL            5.523562
Length: 3423, dtype: float64

In [93]:
NP_TYPE = NP.np.value_counts().to_frame('n')
NP_TYPE['df'] = NPM.astype(bool).sum()
NP_TYPE['dfidf'] = NP_TYPE.df * np.log2(len(NPM)/NP_TYPE.df)

In [98]:
NP_TYPE.sort_values('dfidf', ascending=False).head(10)

             n  df      dfidf
np
HUNAHPU     63  17  24.413685
SI          27  17  24.413685
QUIEN       23  17  24.413685
ESO         19  16  24.376991
BALAMACAB   51  16  24.376991
IXBALANQUE  60  16  24.376991
LA          30  16  24.376991
QUIENES     21  16  24.376991
LOSSENORES  74  18  24.365465
OS          34  18  24.365465

In [67]:
set(NP_TYPE[(NP_TYPE.n > 4) & (NP_TYPE.n < 90)].index.tolist())

{'ABUELA',
 'ADMIRACION',
 'AGUA',
 'AHALPUH',
 'AHPOP',
 'ALEGRIA',
 'ALGO',
 'AMANECER',
 'ANIMALES',
 'AQUELLOS',
 'ARBOL',
 'AVILIX',
 'BALAM-',
 'BALAM-ACAB',
 'BALAM-QUITZE',
 'BARRANCO',
 'CABRACAN',
 'CADA DIA',
 'CADA UNA',
 'CADA UNO',
 'CAMINO',
 'CAVEC',
 'CAVIZIMAH',
 'CERBATANA',
 'CHAMIABAC',
 'CIELO',
 'COMO',
 'CONSEJO',
 'CORAZON DEL CIELO',
 'COTUHA',
 'CUAL',
 'CUYA',
 'CUYOS',
 'DIA',
 'DIOS',
 'DOLOR',
 'EL',
 'EL AHTZIC-VINAC',
 'EL ARBOL',
 'EL BOSQUE',
 'EL CAMINO',
 'EL CIELO',
 'EL CORAZON',
 'EL CREADOR',
 'EL DIA',
 'EL DIOS',
 'EL FONDO',
 'EL FORMADOR',
 'EL FUEGO',
 'EL GAVILAN',
 'EL HOMBRE',
 'EL HOYO',
 'EL JUEGO',
 'EL LEON',
 'EL LUGAR',
 'EL MONTE',
 'EL MUNDO',
 'EL NACIMIENTO',
 'EL NOMBRE',
 'EL ORIENTE',
 'EL PRINCIPIO',
 'EL SAPO',
 'EL SENOR',
 'EL SOL',
 'EL TIGRE',
 'EL VIENTRE',
 'ELLA',
 'ELLAS',
 'EN LA NOCHE',
 'EN LA TIERRA',
 'ESO',
 'ESTA',
 'ESTA MANERA',
 'ESTA RAZON',
 'ESTAS',
 'ESTE',
 'ESTE ARBOL',
 'ESTO',
 'ESTOS',
 'FRIO',
 'GUCUMATZ',
 'HACAVITZ',
 'HIJAS',
 'HIJOS',
 'HOMBRE',
 'HOMBRES',
 'HOYO',
 'HUN-CAME',
 'HUN-HUNAHPU',
 'HUNAHPU',
 'HUNBATZ',
 'HUNCHOUEN',
 'HURACAN',
 'ILOCAB',
 'IQUI-',
 'IQUI-BALAM',
 'IXBALANQUE',
 'IXMUCANE',
 'IXTAH',
 'IZMACHI',
 'JUEGO',
 'LA',
 'LA ABUELA',
 'LA APARIENCIA',
 'LA AURORA',
 'LA BOCA',
 'LA CABEZA',
 'LA CARA',
 'LA CARNE',
 'LA CASA',
 'LA CERBATANA',
 'LA CIMA',
 'LA CIUDAD',
 'LA COLA',
 'LA COMIDA',
 'LA CREACION',
 'LA CULEBRA',
 'LA CUMBRE',
 'LA DONCELLA',
 'LA FAZ',
 'LA FLAUTA',
 'LA GENTE',
 'LA GRANDEZA',
 'LA GUERRA',
 'LA HISTORIA',
 'LA JICARA',
 'LA JOVEN',
 'LA LLEGADA',
 'LA LUNA',
 'LA MANERA',
 'LA MONTANA',
 'LA MUERTE',
 'LA MUJER',
 'LA NOTICIA',
 'LA ORILLA',
 'LA OSCURIDAD',
 'LA PALABRA',
 'LA PELOTA',
 'LA PRUEBA',
 'LA PUNTA',
 'LA RISA',
 'LA SALIDA',
 'LA SANGRE',
 'LA SENAL',
 'LA SUPERFICIE',
 'LA TIERRA',
 'LA VIDA',
 'LA VISTA',
 'LAS',
 'LAS AVES',
 'LAS AVISPAS',
 'LAS CANAS',
 'LAS CARAS',
 'LAS CASAS GRANDES',
 'LAS CIUDADES',
 'LAS ESTRELLAS',
 'LAS FLORES',
 'LAS HORMIGAS',
 'LAS MONTANAS',
 'LAS PIEDRAS',
 'LAS PIERNAS',
 'LAS RAMAS',
 'LAS TRIBUS',
 'LOS ANIMALES',
 'LOS ARBOLES',
 'LOS BEJUCOS',
 'LOS BRAZOS',
 'LOS CAKCHIQUELES',
 'LOS CAMINOS',
 'LOS CAMPOS',
 'LOS CUALES',
 'LOS CUATROCIENTOS MUCHACHOS',
 'LOS DIENTES',
 'LOS DIOSES',
 'LOS DOS MUCHACHOS',
 'LOS HIJOS',
 'LOS HOMBRES',
 'LOS HUESOS',
 'LOS MENSAJEROS',
 'LOS MONTES',
 'LOS MUCHACHOS',
 'LOS MUNECOS',
 'LOS NOMBRES',
 'LOS OJOS',
 'LOS PAJAROS',
 'LOS PROGENITORES',
 'LOS PUEBLOS',
 'LOS QUE',
 'LOS SACERDOTES',
 'LOS SENORES',
 'LOS SENORES DE XIBALBA',
 'LOS ZANGANOS',
 'LUZ',
 'MADRE',
 'MAHUCUTAH',
 'MAIZ',
 'ME',
 'MENSAJEROS',
 'MI',
 'MIEDO',
 'MONTE',
 'MUCHACHOS',
 'MUCHO TIEMPO',
 'MUCHOS',
 'MUERTE',
 'NADA',
 'NIHAIB',
 'NOMBRE',
 'NOS',
 'NOSOTROS',
 'NUESTROS PADRES',
 'OBRA',
 'ORIENTE',
 'OS',
 'OTRO',
 'OTROS',
 'PADRE',
 'PADRES',
 'PAJAROS',
 'PALO',
 'PELOTA',
 'PIEDRAS',
 'PRINCIPIO',
 'PUEBLO',
 'QUICAB',
 'QUICHE',
 'QUIEN',
 'QUIENES',
 'RATON',
 'REINO',
 'REY',
 'REYES',
 'RIO',
 'SACRIFICADORES',
 'SANGRE',
 'SAPO',
 'SE',
 'SEGUIDA',
 'SENOR',
 'SENORES',
 'SI',
 'SIETE DIAS',
 'SOL',
 'SU ABUELA',
 'SU CASA',
 'SU CIUDAD',
 'SU COMIDA',
 'SU DIOS',
 'SU FUEGO',
 'SU GRANDEZA',
 'SU LUGAR',
 'SU MADRE',
 'SU MUERTE',
 'SU MUJER',
 'SU NOMBRE',
 'SU OCOTE',
 'SU PADRE',
 'SU PODER',
 'SU VISTA',
 'SUELO',
 'SUS CASAS',
 'SUS CORAZONES',
 'SUS HIJAS',
 'SUS HIJOS',
 'SUS HUESOS',
 'SUS MUJERES',
 'SUS NOMBRES',
 'SUS OJOS',
 'SUS PADRES',
 'TAL',
 'TAMUB',
 'TEPEPUL',
 'TEPEU',
 'TIERRA',
 'TIGRE',
 'TODAS LAS TRIBUS',
 'TODO',
 'TODO ESTO',
 'TODOS',
 'TODOS LOS ANIMALES',
 'TODOS LOS GUERREROS',
 'TODOS LOS PUEBLOS',
 'TODOS LOS SENORES',
 'TOHIL',
 'TU',
 'TULAN',
 'TZIQUINAHA',
 'UN INSTANTE',
 'UN PRODIGIO',
 'UN RIO',
 'UNA CASA GRANDE',
 'UNO',
 'VASALLOS',
 'VENTURA',
 'VOSOTROS',
 'VUCUB-',
 'VUCUB-CAME',
 'VUCUB-CAQUIX',
 'VUCUB-HUNAHPU',
 'VUELTAS',
 'VUESTRA ABUELA',
 'XIBALBA',
 'YO',
 'ZIPACNA'}

In [61]:
NP[NP.np == 'VUCUB-']

                     np
parte capit
2     1     83   VUCUB-
      2     53   VUCUB-
            118  VUCUB-
            315  VUCUB-
            333  VUCUB-