# Edmonson Chapter Titles

In [1]:
import pandas as pd
import numpy as np
import roman

In [2]:
toc = open("edmonson-toc.md", "r").readlines()

In [3]:
data = []
part_nums = list("ABCD")
for line in toc:
    parts = line.split()
    
    if len(parts) == 5 and parts[3] == 'CREATION':
        part_num = part_nums.index(parts[0][:-1]) + 1
        continue
    
    chap_num = roman.fromRoman(parts[0][:-1])
    chap_line = parts[-1]
    chap_title = ' '.join(parts[1:-1])

    data.append((part_num, chap_num, chap_title, chap_line))

In [4]:
TOC = pd.DataFrame(data, columns=['part_num','chap_num','chap_title','chap_line'])
TOC = TOC.set_index(['chap_num'])

In [5]:
TOC.head()

          part_num                   chap_title chap_line
chap_num
1                1  The Root of the Former Word         1
2                1                  The Silence        95
3                1               The First Word       103
4                1                 The Creation       157
5                1                  The Animals       261

In [6]:
CHRISTENSON = pd.read_csv("../christenson/christenson-CHAP.csv").set_index(['chap_num'])

In [7]:
CHRISTENSON.xom_start_fixed = CHRISTENSON.xom_start_fixed.astype(int)

In [8]:
CHRISTENSON.head()

,chap_title,page_num,xom_start,xom_end,xom_start_fixed,xom_end_fixed
chap_num,,,,,,
1,Preamble,59,1,96,1,96
2,The Primordial World,67,97,154,97,154
3,The Creation of the Earth,70,155,274,155,274
4,The Creation of the Animals,74,275,339,275,339
5,The Fall of the Animals,76,340,433,340,433

In [9]:
pd.set_option('display.max_rows', None)

In [20]:
COMBO = (
    pd.concat([TOC[['chap_title','chap_line','part_num']], 
               CHRISTENSON[['chap_title','xom_start_fixed']]], keys=['ed', 'ch'], axis=1)
    .fillna(0)
)

In [17]:
COMBO[('ch', 'xom_start_fixed')] = COMBO[('ch', 'xom_start_fixed')].astype(int)

In [18]:
COMBO

                                           ed                     \
                                   chap_title chap_line part_num
chap_num
1                 The Root of the Former Word         1        1
2                                 The Silence        95        1
3                              The First Word       103        1
4                                The Creation       157        1
5                                 The Animals       261        1
6                              The Mud People       325        1
7                      The Dolls Made of Wood       505        1
8                                   The Flood       667        1
9                                    7 Parrot       821        2
10                       The Sons of 7 Parrot       891        2
11                The Destruction of 7 Parrot       963        2
12                 Alligator and the 400 Sons      1159        2
13               The Destruction of Alligator      1355        2
14                   The Destruction of 2 Leg      1489        2
15                     Hunter and Jaguar Deer      1675        3
16                      1 Hunter and 7 Hunter      1687        3
17                     The Messengers of Hell      1871        3
18                             Defeat in Hell      1979        3
19                                 The Maiden      2201        3
20                            1 Hunter's Head      2203        3
21                        The Maiden's Escape      2297        3
22                  The Maiden Proves Herself      2421        3
23                     The Birth of the Twins      2567        3
24                      Defeat of the Monkeys      2571        3
25                            The Monkey Song      2791        3
26                           The Monkey Dance      2799        3
27                         The Capture of Rat      2909        3
28                       Recovery of the Ball      3155        3
29                         The Fable of Louse      3219        3
30                        The Message of Hell      3349        3
31                         The Trials of Hell      3431        3
32                       The House of Jaguars      3901        3
33                          The House of Fire      3921        3
34                          The House of Bats      3935        3
35                              The Ball Game      4059        3
36                     The Death of the Twins      4123        3
37                    The Return of the Twins      4253        3
38                     The Invitation of Hell      4285        3
39                                 The Dances      4336        3
40                         The Defeat of Hell      4465        3
41                                  Vengeance      4529        3
42                               Sun and Moon      4659        3
43                            The Idea of Man      4709        4
44                 Yellow Corn and White Corn      4747        4
45                             Cleft Mountain      4751        4
46                          The First Fathers      4823        4
47                Their Perfect Understanding      4895        4
48                    The Concern of the Gods      4955        4
49                                The Peoples      4997        4
50                                       Tula      5249        4
51                             The Storm Gods      5263        4
52                             The First Fire      5297        4
53                      The Messenger of Hell      5365        4
54                      The Suckling of Storm      5479        4
55                           The Three Quiche      5647        4
56                 The Fasting of the Fathers      5670        4
57                     The Watch for the Dawn      5740        4
58                                       Dawn      5909        4
59                        Gods of the Peoples      5913        4
60                             The Sacrifices      6157        4
61                        The Stealing of Men      6369        4
62                      Seizure of the Tribes      6375        4
63                     The Plan of the Tribes      6463        4
64                     The Girls and the Gods      6532        4
65                      The Signs of the Gods      6637        4
66                        The Tribes Make War      6782        4
67                   The Defeat of the Tribes      6939        4
68                       Death of the Fathers      7071        4
69                      The Second Generation      7229        4
70                     The Insignia of Naxcit      7280        4
71                  Wanderings from Fire Peak      7319        4
72                      Beard and Rotten Cane      7417        4
73                            The Kavek Lords      7667        4
74                            The Nine Kaveks      7678        4
75                      The Great-House Lords      7681        4
76                            The Lord Quiche      7693        4
77                            The White Winds      7701        4
78                          Feathered Serpent      7707        4
79                                      Blood      7819        4
80                         Conquests of Blood      7905        4
81                                  The Ranks      8051        4
82                             The New Titles      8055        4
83                                The Temples      8103        4
84                         Prayer and Fasting      8197        4
85                The Succession of the Lords      8359        4
86                            The Kavek Lords      8383        4
87                     The Kavek Great Houses      8423        4
88                            The Nine Kaveks      8457        4
89                 The Great-House Succession      8463        4
90                      The Great-House Lords      8471        4
91                     The Great-House Houses      8499        4
92                      The Nine Great-Houses      8523        4
93                            The Lord Quiche      8531        4
94                      The Four Lord Quiches      8547        4
95        The Great Houses of the Lord Quiche      8553        4
96                         The Great Chairmen      8563        4
97                                     Quiche      8573        4

                                                         ch
                                                 chap_title xom_start_fixed
chap_num
1                                                  Preamble               1
2                                      The Primordial World              97
3                                 The Creation of the Earth             155
4                               The Creation of the Animals             275
5                                   The Fall of the Animals             340
6                            The Creation of the Mud Person             434
7               The Creation of the Effigies of Carved Wood             518
8                   The Fall of the Effigies of Carved Wood             680
9                  The Pride of Seven Macaw Before the Dawn             838
10                     The Fall of Seven Macaw and His Sons             908
11                                The Defeat of Seven Macaw             985
12           The Deeds of Zipacna and the Four Hundred Boys            1189
13                                    The Defeat of Zipacna            1386
14                                   The Defeat of Cabracan            1525
15          The Tale of the Father of Hunahpu and Xbalanque            1721
16        The Deeds of One Hunahpu and Seven Hunahpu Abo...            1733
17        The Summons of One Hunahpu and Seven Hunahpu t...            1919
18        The Descent of One Hunahpu and Seven Hunahpu i...            2033
19        The Maiden Lady Blood and the Tree of One Hunahpu            2268
20                    The Ascent of Lady Blood from Xibalba            2375
21                  Lady Blood and the Miracle of the Maize            2510
22        Hunahpu and Xbalanque in the House of the Gran...            2664
23                      The Fall of One Batz and One Chouen            2900
24                  Hunahpu and Xbalanque in the Maizefield            3024
25         Hunahpu and Xbalanque Discover the Gaming Things            3273
26          The Summons of Hunahpu and Xbalanque to Xibalba            3339
27        Hunahpu and Xbalanque Receive the Summons to X...            3470
28        The Descent of Hunahpu and Xbalanque into Xibalba            3557
29               Hunahpu and Xbalanque in the House of Cold            3994
30            Hunahpu and Xbalanque in the House of Jaguars            4018
31               Hunahpu and Xbalanque in the House of Fire            4038
32               Hunahpu and Xbalanque in the House of Bats            4052
33                          The Head of Hunahpu is Restored            4178
34                      The Deaths of Hunahpu and Xbalanque            4242
35                The Resurrection of Hunahpu and Xbalanque            4366
36        The Summons of Hunahpu and Xbalanque Before th...            4399
37        Hunahpu and Xbalanque Dance Before the Lords o...            4448
38                       The Defeat of the Lords of Xibalba            4574
39            The Miraculous Maize of Hunahpu and Xbalanque            4640
40               The Apotheosis of the Sun, Moon, and Stars            4773
41                                 The Creation of Humanity            4822
42                                   The Discovery of Maize            4862
43                                       The First Four Men            4940
44                   The Miraculous Vision of the First Men            4948
45                           The Gratitude of the First Men            5011
46                              The Displeasure of the Gods            5072
47         The Creation of the Mothers of the Quiché Nation            5116
48                                     The Arrival at Tulan            5371
49                       The Progenitors Receive their Gods            5385
50                              The Progenitors Leave Tulan            5424
51                           The Nations Ask for their Fire            5496
52        The Nations Are Deceived into Offering Themselves            5612
53              The People Gather on the Mountain Chi Pixab            5785
54                Their Suffering on the Mountain Chi Pixab            5807
55                     The Progenitors Await the First Dawn            5881
56                         The Appearance of the First Dawn            6054
57                           Offerings Are Made to the Gods            6300
58                           The Sacrificial Killings Begin            6514
59                      The Nations Plot to Seduce the Gods            6608
60              The Seduction of Lady Lust and Lady Wailing            6710
61            The Nations Are Defeated by the Painted Robes            6786
62                               The Nations Are Humiliated            6930
63                                 The Nations Are Defeated            7086
64                       The Deaths of the Four Progenitors            7217
65             The Sons of the Progenitors Journey to Tulan            7371
66                       The Sons Receive Authority to Rule            7422
67                            The Migrations of the Quichés            7461
68                            The Foundation of Chi Izmachi            7560
69                               The Foundation of Cumarcah            7718
70                            The Titles of the Cavec Lords            7798
71                           The Titles of the Nihaib Lords            7813
72                      The Titles of the Ahau Quiché Lords            7825
73                           The Titles of the Zaquic Lords            7833
74                       The Glory of the Lords of Cumarcah            7839
75                             The Victories of Lord Quicab            7954
76               The Quichés Garrison the Conquered Regions            8043
77              The Titles Given to Those Who Were Ennobled            8191
78                            The Names of the Gods’ Houses            8242
79                    The Prayer of the Lords to their Gods            8336
80                          The Generations of Quiché Lords            8501
81                        The Dynasty of Cavec Quiché Lords            8526
82                      The Great Houses of the Cavec Lords            8566
83                              The Dynasty of Nihaib Lords            8606
84                     The Great Houses of the Nihaib Lords            8642
85                         The Dynasty of Ahau Quiché Lords            8674
86                The Great Houses of the Ahau Quiché Lords            8690
87          The Three Great Stewards as Mothers of the Word            8706
88                                                        0               0
89                                                        0               0
90                                                        0               0
91                                                        0               0
92                                                        0               0
93                                                        0               0
94                                                        0               0
95                                                        0               0
96                                                        0               0
97                                                        0               0