# Colop Glossary

In [1]:
import pandas as pd
import numpy as np

In [5]:
GLOSS = pd.read_csv("colop-glossary.txt", sep="|").set_index('term')

In [6]:
GLOSS

                                                                           gloss
term
ACHAQ' IBOY                    Debe ser *Uchaq' Iboy*, "hermano menor armadil...
AJAL MES                       Señor de Xibalba, causante de desgracias, prov...
AJAL PUJ                       Señor de Xibalba, quien junto con Ajal Q'ana, ...
AJAL Q'ANA                     Señor de Xibalba, quien junto con Ajal Puj, hi...
AJAL TOQ'OB                    Señor de Xibalba, que hería a la gente y junto...
...                                                                          ...
XIKIRIPAT                      Señor de Xibalba, quien, junto con Kuchuma Kik...
XPIYAKOK                       Nombre de origen náhuatl. Junto con Ixmukane, ...
XULU                           El otro adivino que, junto con Pak'am, recibe ...
YA'XKANUL                      Volcán en el agua y por eso puede ser uno de l...
YAKOLATAM UTZA'M POP SAQLATOL  Título de uno de los Señores principales frent...

[193 rows x 1 columns]

In [9]:
DOC = pd.read_csv("colop-DOC.csv").set_index(['parte','capit'])

# CCC

In [141]:
matches = []
for doc in DOC.iterrows():
    doc_id = doc[0]
    doc_str = doc[1].doc_str.lower()
    for gloss in GLOSS.iterrows():
        gloss_str = gloss[0].lower()
        if gloss_str in doc_str:
            matches.append((doc_id[0], doc_id[1], gloss[0]))
CCC = pd.DataFrame(matches, columns=['parte','capit','term'])
CCC.index.name = 'ccc_id'

In [142]:
CCC

        parte  capit           term
ccc_id
0           1      1           ALOM
1           1      1        JUNAJPU
2           1      1   JUNAJPU UTIW
3           1      1  JUNAJPU WUCH'
4           1      1       K'AJOLOM
...       ...    ...            ...
365         5     13            XIK
366         5     14   AJAW K'ICHE'
367         5     15   AJAW K'ICHE'
368         5     15          KAWEQ
369         5     15        NIJA'IB

[370 rows x 3 columns]

In [143]:
PAIR = CCC.merge(CCC, on=['parte','capit'])\
    .value_counts(['term_x','term_y'])\
    .unstack(fill_value=0).corr('kendall')

In [162]:
PAIR['SUYWA'].sort_values(ascending=False).head(20)

term_y
SUYWA              1.000000
K'ELETZU           0.871074
KAWISTAN POM       0.871074
MIXTAM POM         0.871074
NIK'AQAJ TAQ'AJ    0.794153
CHI PIXAB          0.794153
AWILIX             0.712952
TOJIL              0.656359
TUJAL JA           0.580854
TAMUB              0.484730
ILOKAB             0.453536
PISOM Q'AQ'AL      0.357593
WILA               0.312159
KAWEQ              0.235519
KANCHAJELEB        0.233287
LAMAKIB            0.233287
CH'IPI NANAWAK     0.233287
SAQAJIB            0.233287
RAXA NANAWAK       0.233287
AKUL WINAQ         0.233287
Name: SUYWA, dtype: float64

In [127]:
PAIR2 = PAIR.stack().to_frame('r')

In [128]:
PAIR2.index.names = ['x','y']

In [153]:
PAIR3 = PAIR2.query("x < y").sort_values('r', ascending=False)

In [154]:
PAIR3[PAIR3.r > .8]

                                  r
x            y
TZ'OLOJ CHE' WAJXALAJUJ    1.000000
KANCHAJELEB  SAQAJIB       1.000000
             WOK, JUNAJPU  1.000000
AJAL MES     AJAL TOQ'OB   1.000000
TZ'OLOJ CHE' UTZA'M ACHIJ  1.000000
...                             ...
AJAL Q'ANA   KUCHUMA KIK'  0.810582
CHIMALMAT    JULISNAB      0.807958
             MAKAMOB       0.807958
AJAL Q'ANA   JUN RAQAN     0.803010
AJAL PUJ     JUN RAQAN     0.803010

[222 rows x 1 columns]

# Save

In [47]:
for df in [(GLOSS, 'GLOSS'), (PAIR,'CCCPAIR')]:
    df[0].to_csv(f"colop-{df[1]}.csv", index=True)