# Colop Ngrams

In [7]:
import pandas as pd
import numpy as np
import nltk
from nltk.util import ngrams
# import spacy

In [6]:
DOC = pd.read_csv("colop-DOC.csv").set_index(['parte','capit'])

In [20]:
SENT = DOC.doc_str.apply(nltk.sent_tokenize).apply(pd.Series).stack().to_frame('sent_str')
SENT.index.names = ['parte','capit','sent']

In [21]:
SENT

                                                           sent_str
parte capit sent
1     1     0     ARE' UXE' OJER TZIJ WARAL K'ICHE' UB'I' Waral ...
            1     Are k'ut xchiqak'am wi: uk'utunisaxik, uq'alaj...
            2     Junajpu Wuch', Junajpu Utiw, Saqinim Aq Sis Te...
            3     Chucha'xik, rachb'ixik, rachtzijoxik ri Iyom, ...
            4          Matzanel, Chuqenel, Kamul Iyom, Kamul Mamom.
...                                                             ...
5     15    5     Xare k'ut uk'oje'ik K'iche' ri' rumal maja b'i...
            6                       K'o nab'e, ojer, kumal ajawab'.
            7                                        Sachinaq chik.
            8      Xere k'u ri mixutzinik chi konojel K'iche', Sta.
            9                                          Cruz, ub'i'.

[2820 rows x 1 columns]

In [102]:
BG = SENT.sent_str.str.replace(r"[^A-Za-z' ]", "", regex=True).str.replace("-","")\
    .str.split()\
    .apply(lambda x: list(ngrams(x, 2)))\
    .apply(pd.Series).stack()\
    .apply(pd.Series)

In [103]:
BG_DOC = TG.groupby(['parte','capit']).value_counts().to_frame('n')

In [104]:
BG_DOC[BG_DOC.n > 2]

                              n
parte capit 0      1
1     2     k'o    wi         5
            Tepew  Q'ukumatz  4
            Uk'ux  Kaj        3
            naki   la'        3
            ri     Tepew      3
...                          ..
5     13    Q'amja jun        4
      14    unim   ja         5
            ajaw   jun        4
            jun    unim       4
      15    Nim    Chokoj     3

[712 rows x 1 columns]

In [106]:
BG_COUNT = TG.value_counts().to_frame('n')

In [118]:
BG_COUNT[BG_COUNT.n > 3].sort_index().tail(30)

                      n
0           1
xeb'e       chi       4
            chik      4
            k'ut      5
xeb'ek      e         4
xech'akataj wi        6
xecha'      k'ut      5
xek'oje     wi        9
xekam       wi        5
xel         k'u       4
            wi        4
xepe        wi        6
xere        chi       5
            uwach     4
xk'am       kina'oj   6
xk'astaj    uwach     4
xk'oje      wi       10
xkib'an     chik      4
xkib'ij     k'ut      4
xkik'am     k'ut      4
            wi        4
xkil        ri        4
xma         k'o       5
xojpe       wi        4
xok         chi       4
xopon       k'ut      5
xpe         k'ut      4
            wi        9
xsaqir      wi        4
xtiy        chik      7
xya'        uloq      4

In [121]:
# BG_COUNT.loc['Wuqub']