In [1]:
import pandas as pd

In [2]:
src = "../../textos/tedlock-text-only.txt"

In [3]:
lines = [line.strip() for line in open(src,'r').readlines()]

In [4]:
LINE = pd.DataFrame(lines, columns=['line_str'])
LINE.loc[LINE.line_str.str.match("^\s*PART"), 'part'] = LINE.line_str
LINE.part = LINE.part.ffill()
LINE = LINE[~LINE.line_str.str.match("^\s*PART")]

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
/var/folders/fb/hhf80dqn5x190kxk7_y8557r0000gq/T/ipykernel_58638/3406135841.py:2: SyntaxWarning: invalid escape sequence '\s'
  LINE.loc[LINE.line_str.str.match("^\s*PART"), 'part'] = LINE.line_str
/var/folders/fb/hhf80dqn5x190kxk7_y8557r0000gq/T/ipykernel_58638/3406135841.py:4: SyntaxWarning: invalid escape sequence '\s'
  LINE = LINE[~LINE.line_str.str.match("^\s*PART")]

In [5]:
replacers = {f"PART {num}":i+1 for i, num in enumerate("ONE TWO THREE FOUR FIVE".split())}

In [6]:
replacers

{'PART ONE': 1, 'PART TWO': 2, 'PART THREE': 3, 'PART FOUR': 4, 'PART FIVE': 5}

In [7]:
LINE.part = LINE.part.map(replacers)

In [12]:
LINE

                                               line_str  part
1     THIS IS THE BEGINNING OF THE ANCIENT WORD, her...     1
2     called Quiche. Here we shall inscribe, we shal...     1
3     Ancient Word, the potential and source for eve...     1
4     citadel of Quiche, in the nation of Quiche peo...     1
5     And here we shall take up the demonstration, r...     1
...                                                 ...   ...
3897  THIS IS ENOUGH ABOUT THE BEING OF QUICHE, give...     5
3898  longer a place to see it. There is the origina...     5
3899  writing owned by the lords, now lost, but even...     5
3900  has been completed here concerning Quiche, whi...     5
3901                                              Cruz.     5

[3897 rows x 2 columns]

In [9]:
PART = LINE.groupby(['part']).line_str.apply(lambda x: ' '.join(map(str,x))).to_frame('part_str')

In [10]:
PART

                                               part_str
part
1     THIS IS THE BEGINNING OF THE ANCIENT WORD, her...
2     HERE IS THE BEGINNING OF THE DEFEAT AND DESTRU...
3     AND NOW WE SHALL NAME THE NAME OF THE FATHER O...
4     AND HERE IS THE BEGINNING OF THE CONCEPTION OF...
5     AND THEN THEY REMEMBERED WHAT HAD BEEN SAID AB...

In [13]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [17]:
SENT = PART.part_str.apply(nlp).apply(lambda x: [sent for sent in x.sents])\
    .apply(pd.Series).stack().to_frame('sent_str')
SENT.index.names = PART.index.names[:1] + ['sent']
SENT = SENT.dropna()

In [19]:
SENT

                                                    sent_str
part sent
1    0     (THIS, IS, THE, BEGINNING, OF, THE, ANCIENT, W...
     1     (Here, we, shall, inscribe, ,, we, shall, impl...
     2     (And, here, we, shall, take, up, the, demonstr...
     3     (They, accounted, for, everythingand, did, it,...
     4     (We, shall, write, about, this, now, amid, the...
...                                                      ...
5    415   (And, Great, Toastmaster, for, the, Greathouse...
     416   (Great, Toastmaster, Lord, for, the, Lord, Qui...
     417   (And, so, there, are, three, Toastmasters, ,, ...
     418   (THIS, IS, ENOUGH, ABOUT, THE, BEING, OF, QUIC...
     419   (There, is, the, original, book, and, ancient,...

[2799 rows x 1 columns]

In [ ]:
TOKEN = SENT.sent_str.apply(lambda x: [[token.text, token.pos_, token.dep_] for token in x])\
    .apply(pd.Series).stack()\
    .apply(pd.Series)
TOKEN.columns = ['token_str','token_pos','token_dep']
TOKEN.index.names = TOKEN.index.names[:2] + ['token_num']

In [24]:
TOKEN = TOKEN.dropna()

In [25]:
TOKEN

                     token_str token_pos token_dep   term_str
part sent token_num
1    0    0               THIS      PRON     nsubj       this
          1                 IS       AUX      ROOT         is
          2                THE       DET       det        the
          3          BEGINNING      NOUN      attr  beginning
          4                 OF       ADP      prep         of
...                        ...       ...       ...        ...
5    419  30               now       ADV    advmod        now
          31             named      VERB     relcl      named
          32             Santa     PROPN  compound      santa
          33              Cruz     PROPN      oprd       cruz
          34                 .     PUNCT     punct          .

[48076 rows x 4 columns]

In [26]:
TOKEN['term_str'] = TOKEN.token_str.str.lower().str.replace(f"\W+", "")
TOKEN.term_str

<>:1: SyntaxWarning: invalid escape sequence '\W'
<>:1: SyntaxWarning: invalid escape sequence '\W'
/var/folders/fb/hhf80dqn5x190kxk7_y8557r0000gq/T/ipykernel_58638/2044551504.py:1: SyntaxWarning: invalid escape sequence '\W'
  TOKEN['term_str'] = TOKEN.token_str.str.lower().str.replace(f"\W+", "")

part  sent  token_num
1     0     0                 this
            1                   is
            2                  the
            3            beginning
            4                   of
                           ...
5     419   30                 now
            31               named
            32               santa
            33                cruz
            34                   .
Name: term_str, Length: 48076, dtype: str

In [40]:
DOCRAW = TOKEN.groupby(['part','sent']).token_str.apply(lambda x: ' '.join(map(str,x)))\
    .to_frame('doc_str').reset_index()
DOCRAW.index.name = 'doc_id'
DOCRAW

        part  sent                                            doc_str
doc_id
0          1     0  THIS IS THE BEGINNING OF THE ANCIENT WORD , he...
1          1     1  Here we shall inscribe , we shall implant the ...
2          1     2  And here we shall take up the demonstration , ...
3          1     3  They accounted for everythingand did it , too-...
4          1     4  We shall write about this now amid the preachi...
...      ...   ...                                                ...
2794       5   415  And Great Toastmaster for the Greathouses , se...
2795       5   416  Great Toastmaster Lord for the Lord Quiches , ...
2796       5   417  And so there are three Toastmasters , one repr...
2797       5   418  THIS IS ENOUGH ABOUT THE BEING OF QUICHE , giv...
2798       5   419  There is the original book and ancient writing...

[2799 rows x 3 columns]

In [44]:
doc_idx = ['part', 'sent']
DOC = DOCRAW[['doc_str']]
DOCMAP = DOCRAW[doc_idx]

In [45]:
DOC.to_csv("tedlock-DOC.csv", index=True)
DOCMAP.to_csv("tedlock-DOCMAP.csv", index=True)

In [46]:
with open(f"tedlock-DOC_idx.txt", "w") as out:
    out.write(",".join(DOCMAP.columns))

In [47]:
TOKEN.to_csv(f"tedlock-TOKEN.csv", index=True)